#!/bin/bash

echo "🔧 FIX GOOGLE OAUTH - REDIRECT URI MISMATCH"
echo "==========================================="
echo ""
echo "The error 'redirect_uri_mismatch' means Google OAuth is rejecting the login"
echo "because the redirect URL from Supabase isn't in your Google OAuth config."
echo ""
echo "📍 CRITICAL URL TO ADD:"
echo "   https://issmshemlkrucmxcvibs.supabase.co/auth/v1/callback"
echo ""
echo "STEP-BY-STEP FIX:"
echo ""
echo "1. Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/apis/credentials"
echo ""
echo "2. Find your OAuth 2.0 Client ID (should be for 'fortress.games' or similar)"
echo ""
echo "3. Click on it to edit"
echo ""
echo "4. In 'Authorized redirect URIs' section, ADD this EXACT URL:"
echo "   https://issmshemlkrucmxcvibs.supabase.co/auth/v1/callback"
echo ""
echo "5. Also add these for local development and production:"
echo "   http://localhost:8081/auth/callback"
echo "   http://localhost:8081/login"  
echo "   https://your-netlify-app.netlify.app/auth/callback"
echo "   https://your-netlify-app.netlify.app/login"
echo ""
echo "6. Click 'SAVE' at the bottom"
echo ""
echo "7. IMPORTANT: Changes can take 5-10 minutes to propagate!"
echo ""
echo "8. After saving, try the login again"
echo ""
echo "==========================================="
echo ""
echo "🔍 DEBUGGING TIP:"
echo "If it still doesn't work after adding the URL, check:"
echo "1. Is the URL EXACTLY correct? (no trailing slash, correct project ID)"
echo "2. Did you save the changes in Google Cloud Console?"
echo "3. Have you waited 5-10 minutes for changes to propagate?"
echo "4. Clear browser cache/cookies and try again"
echo ""
