#!/bin/bash

echo "🔒 Supabase Publishable Key & RLS Setup Guide"
echo "=============================================="
echo ""
echo "You have a new Supabase Publishable Key:"
echo "sb_publishable_eDwuQxq1a0EciAfbDQtskQ_AEbsF5mC"
echo ""
echo "⚠️  IMPORTANT: This key ONLY works with RLS enabled!"
echo ""
echo "📋 Steps to Enable RLS and Use the Publishable Key:"
echo ""
echo "1️⃣  CHECK RLS STATUS:"
echo "   Go to: https://supabase.com/dashboard/project/issmshemlkrucmxcvibs/editor"
echo "   Run this SQL query:"
echo "   SELECT tablename, rowsecurity FROM pg_tables WHERE schemaname = 'public';"
echo ""
echo "2️⃣  ENABLE RLS ON ALL TABLES:"
echo "   Run the SQL script: ENABLE-RLS.sql"
echo "   Or use Supabase Dashboard → Authentication → Policies"
echo ""
echo "3️⃣  UPDATE YOUR APPLICATION:"
echo ""
echo "   Option A: Use the traditional anon key (works with or without RLS)"
echo "   ---------"
echo "   In .env and app.config.ts:"
echo "   VITE_SUPABASE_ANON_KEY=your_anon_key_from_supabase"
echo ""
echo "   Option B: Use the new publishable key (REQUIRES RLS)"
echo "   ---------"
echo "   In .env and app.config.ts:"
echo "   VITE_SUPABASE_PUBLISHABLE_KEY=sb_publishable_eDwuQxq1a0EciAfbDQtskQ_AEbsF5mC"
echo ""
echo "   Then update your Supabase client initialization:"
echo "   const supabase = createClient(url, publishableKey)"
echo ""
echo "⚠️  CURRENT STATUS:"
echo "   - Your app likely doesn't have RLS enabled (based on the audit)"
echo "   - This is why data access is unrestricted"
echo "   - Enabling RLS will secure your data but may break queries initially"
echo ""
echo "🔧 RECOMMENDATION:"
echo "   1. First, use the regular anon key to get OAuth working"
echo "   2. Then enable RLS table by table with proper policies"
echo "   3. Finally, switch to the publishable key for enhanced security"
echo ""
echo "📚 Learn more about RLS:"
echo "   https://supabase.com/docs/guides/auth/row-level-security"
