-- Enhanced Supabase Migration Schema
-- Generated by Multi-AI Analysis (Claude Code + Gemini CLI)
-- Fortress Modeler Cloud -> Supabase Migration

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "citext"; -- Case-insensitive text for emails

-- =====================================================
-- SUPABASE AUTH INTEGRATION
-- =====================================================

-- Profiles table (replaces users table, links to auth.users)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email CITEXT UNIQUE NOT NULL,
    name VARCHAR(255),
    picture TEXT,
    company_domain VARCHAR(255),
    preferences JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- CORE APPLICATION TABLES
-- =====================================================

-- Projects table (enhanced with RLS and performance optimizations)
CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    product_type VARCHAR(255) NOT NULL,
    target_audience TEXT,
    
    -- Enhanced data structure (Gemini optimization)
    data JSONB DEFAULT '{}'::jsonb,
    timeline JSONB DEFAULT '{}'::jsonb, -- {startDate, endDate}
    avatar_image TEXT,
    
    -- Sharing and visibility (enhanced for real-time collaboration)
    is_public BOOLEAN DEFAULT false,
    owner_email CITEXT,
    share_count INTEGER DEFAULT 0,
    
    -- Timestamps and versioning
    version INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL -- Soft deletes
);

-- Financial models table (optimized for complex JSONB operations)
CREATE TABLE IF NOT EXISTS financial_models (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    
    -- Enhanced assumptions structure with performance indexes
    assumptions JSONB DEFAULT '{}'::jsonb,
    results_cache JSONB DEFAULT '{}'::jsonb, -- Cached calculations (Gemini suggestion)
    
    -- Metadata and versioning
    version INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL
);

-- Actual performance tracking (enhanced for time-series data)
CREATE TABLE IF NOT EXISTS actual_performance (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Actuals period entries (for detailed tracking)
CREATE TABLE IF NOT EXISTS actuals_period_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    period VARCHAR(20) NOT NULL, -- "2024-01", "2024-Q1", etc.
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Ensure unique periods per project
    UNIQUE(project_id, period)
);

-- Risk management (enhanced categorization)
CREATE TABLE IF NOT EXISTS risks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN ('financial', 'operational', 'strategic', 'regulatory', 'other')),
    likelihood VARCHAR(20) NOT NULL CHECK (likelihood IN ('low', 'medium', 'high')),
    impact VARCHAR(20) NOT NULL CHECK (impact IN ('low', 'medium', 'high')),
    status VARCHAR(20) NOT NULL DEFAULT 'identified' CHECK (status IN ('identified', 'mitigated', 'accepted', 'transferred')),
    mitigation TEXT,
    notes TEXT,
    owner_email CITEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Scenario planning (enhanced for complex modeling)
CREATE TABLE IF NOT EXISTS scenarios (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    model_id UUID NOT NULL REFERENCES financial_models(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    assumptions JSONB NOT NULL DEFAULT '{}'::jsonb,
    results JSONB DEFAULT '{}'::jsonb, -- Cached scenario results
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- COLLABORATION AND SHARING
-- =====================================================

-- Project sharing (enhanced for real-time collaboration)
CREATE TABLE IF NOT EXISTS project_shares (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    owner_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    shared_with_email CITEXT NOT NULL,
    shared_with_id UUID REFERENCES profiles(id) ON DELETE CASCADE, -- Resolved user
    permission VARCHAR(20) NOT NULL DEFAULT 'view' CHECK (permission IN ('view', 'edit', 'admin')),
    
    -- Real-time presence tracking
    last_accessed TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT false,
    
    -- Expiration and status
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NULL,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
    
    UNIQUE(project_id, shared_with_email)
);

-- Real-time presence tracking
CREATE TABLE IF NOT EXISTS presence (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    model_id UUID REFERENCES financial_models(id) ON DELETE CASCADE,
    
    -- Presence data
    status VARCHAR(20) NOT NULL DEFAULT 'online' CHECK (status IN ('online', 'away', 'offline')),
    current_page VARCHAR(255),
    cursor_position JSONB,
    
    -- Timestamps
    last_seen TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- PERFORMANCE OPTIMIZATIONS (Gemini Recommendations)
-- =====================================================

-- Indexes for performance (based on query patterns)
CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_user_public ON projects(user_id, is_public);
CREATE INDEX IF NOT EXISTS idx_projects_updated_at ON projects(updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_financial_models_project_id ON financial_models(project_id);
CREATE INDEX IF NOT EXISTS idx_financial_models_user_id ON financial_models(user_id);
CREATE INDEX IF NOT EXISTS idx_financial_models_updated_at ON financial_models(updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_actual_performance_project_date ON actual_performance(project_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_actuals_period_project ON actuals_period_entries(project_id, period);

CREATE INDEX IF NOT EXISTS idx_risks_project_status ON risks(project_id, status);
CREATE INDEX IF NOT EXISTS idx_scenarios_model_id ON scenarios(model_id);

CREATE INDEX IF NOT EXISTS idx_project_shares_project ON project_shares(project_id);
CREATE INDEX IF NOT EXISTS idx_project_shares_email ON project_shares(shared_with_email);
CREATE INDEX IF NOT EXISTS idx_project_shares_user ON project_shares(shared_with_id);

CREATE INDEX IF NOT EXISTS idx_presence_project ON presence(project_id, status);
CREATE INDEX IF NOT EXISTS idx_presence_user_active ON presence(user_id, last_seen DESC);

-- JSONB indexes for performance (Gemini optimization)
CREATE INDEX IF NOT EXISTS idx_projects_data_gin ON projects USING GIN (data);
CREATE INDEX IF NOT EXISTS idx_models_assumptions_gin ON financial_models USING GIN (assumptions);
CREATE INDEX IF NOT EXISTS idx_models_results_gin ON financial_models USING GIN (results_cache);
CREATE INDEX IF NOT EXISTS idx_actuals_data_gin ON actuals_period_entries USING GIN (data);

-- Specific JSONB path indexes for common queries
CREATE INDEX IF NOT EXISTS idx_projects_timeline ON projects USING GIN ((data->'timeline'));
CREATE INDEX IF NOT EXISTS idx_models_revenue ON financial_models USING GIN ((assumptions->'revenue'));
CREATE INDEX IF NOT EXISTS idx_models_costs ON financial_models USING GIN ((assumptions->'costs'));

-- =====================================================
-- FUNCTIONS AND TRIGGERS
-- =====================================================

-- Updated at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply updated_at triggers to all tables
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_projects_updated_at ON projects;
CREATE TRIGGER update_projects_updated_at BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_financial_models_updated_at ON financial_models;
CREATE TRIGGER update_financial_models_updated_at BEFORE UPDATE ON financial_models
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_actual_performance_updated_at ON actual_performance;
CREATE TRIGGER update_actual_performance_updated_at BEFORE UPDATE ON actual_performance
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_actuals_period_entries_updated_at ON actuals_period_entries;
CREATE TRIGGER update_actuals_period_entries_updated_at BEFORE UPDATE ON actuals_period_entries
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_risks_updated_at ON risks;
CREATE TRIGGER update_risks_updated_at BEFORE UPDATE ON risks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_scenarios_updated_at ON scenarios;
CREATE TRIGGER update_scenarios_updated_at BEFORE UPDATE ON scenarios
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Profile creation trigger (auto-create profile on auth signup)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, name)
    VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'name', ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =====================================================
-- ROW LEVEL SECURITY (Enhanced Multi-AI Policies)
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE financial_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE actual_performance ENABLE ROW LEVEL SECURITY;
ALTER TABLE actuals_period_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE risks ENABLE ROW LEVEL SECURITY;
ALTER TABLE scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE presence ENABLE ROW LEVEL SECURITY;

-- Profiles policies (users can only see/edit their own profile)
DROP POLICY IF EXISTS profiles_select_own ON profiles;
CREATE POLICY profiles_select_own ON profiles
    FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS profiles_update_own ON profiles;
CREATE POLICY profiles_update_own ON profiles
    FOR UPDATE USING (auth.uid() = id);

-- Projects policies (enhanced for sharing)
DROP POLICY IF EXISTS projects_select_policy ON projects;
CREATE POLICY projects_select_policy ON projects
    FOR SELECT USING (
        user_id = auth.uid() OR -- Owner
        is_public = true OR -- Public projects
        id IN ( -- Shared projects
            SELECT project_id FROM project_shares 
            WHERE shared_with_id = auth.uid() AND status = 'accepted'
        )
    );

DROP POLICY IF EXISTS projects_insert_policy ON projects;
CREATE POLICY projects_insert_policy ON projects
    FOR INSERT WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS projects_update_policy ON projects;
CREATE POLICY projects_update_policy ON projects
    FOR UPDATE USING (
        user_id = auth.uid() OR -- Owner
        id IN ( -- Edit permission
            SELECT project_id FROM project_shares 
            WHERE shared_with_id = auth.uid() 
            AND permission IN ('edit', 'admin') 
            AND status = 'accepted'
        )
    );

DROP POLICY IF EXISTS projects_delete_policy ON projects;
CREATE POLICY projects_delete_policy ON projects
    FOR DELETE USING (user_id = auth.uid()); -- Only owner can delete

-- Financial models policies (inherit project permissions)
DROP POLICY IF EXISTS financial_models_select_policy ON financial_models;
CREATE POLICY financial_models_select_policy ON financial_models
    FOR SELECT USING (
        user_id = auth.uid() OR
        project_id IN (
            SELECT id FROM projects WHERE 
            user_id = auth.uid() OR 
            is_public = true OR
            id IN (SELECT project_id FROM project_shares WHERE shared_with_id = auth.uid() AND status = 'accepted')
        )
    );

DROP POLICY IF EXISTS financial_models_insert_policy ON financial_models;
CREATE POLICY financial_models_insert_policy ON financial_models
    FOR INSERT WITH CHECK (
        user_id = auth.uid() AND
        project_id IN (
            SELECT id FROM projects WHERE 
            user_id = auth.uid() OR
            id IN (SELECT project_id FROM project_shares WHERE shared_with_id = auth.uid() AND permission IN ('edit', 'admin') AND status = 'accepted')
        )
    );

DROP POLICY IF EXISTS financial_models_update_policy ON financial_models;
CREATE POLICY financial_models_update_policy ON financial_models
    FOR UPDATE USING (
        user_id = auth.uid() OR
        project_id IN (
            SELECT id FROM projects WHERE 
            user_id = auth.uid() OR
            id IN (SELECT project_id FROM project_shares WHERE shared_with_id = auth.uid() AND permission IN ('edit', 'admin') AND status = 'accepted')
        )
    );

-- Apply similar policies to other tables
DROP POLICY IF EXISTS actual_performance_policy ON actual_performance;
CREATE POLICY actual_performance_policy ON actual_performance
    FOR ALL USING (
        user_id = auth.uid() OR
        project_id IN (
            SELECT id FROM projects WHERE 
            user_id = auth.uid() OR 
            id IN (SELECT project_id FROM project_shares WHERE shared_with_id = auth.uid() AND status = 'accepted')
        )
    );

DROP POLICY IF EXISTS actuals_period_policy ON actuals_period_entries;
CREATE POLICY actuals_period_policy ON actuals_period_entries
    FOR ALL USING (
        user_id = auth.uid() OR
        project_id IN (
            SELECT id FROM projects WHERE 
            user_id = auth.uid() OR 
            id IN (SELECT project_id FROM project_shares WHERE shared_with_id = auth.uid() AND status = 'accepted')
        )
    );

DROP POLICY IF EXISTS risks_policy ON risks;
CREATE POLICY risks_policy ON risks
    FOR ALL USING (
        user_id = auth.uid() OR
        project_id IN (
            SELECT id FROM projects WHERE 
            user_id = auth.uid() OR 
            id IN (SELECT project_id FROM project_shares WHERE shared_with_id = auth.uid() AND status = 'accepted')
        )
    );

DROP POLICY IF EXISTS scenarios_policy ON scenarios;
CREATE POLICY scenarios_policy ON scenarios
    FOR ALL USING (
        user_id = auth.uid() OR
        project_id IN (
            SELECT id FROM projects WHERE 
            user_id = auth.uid() OR 
            id IN (SELECT project_id FROM project_shares WHERE shared_with_id = auth.uid() AND status = 'accepted')
        )
    );

-- Project sharing policies
DROP POLICY IF EXISTS project_shares_select_policy ON project_shares;
CREATE POLICY project_shares_select_policy ON project_shares
    FOR SELECT USING (
        owner_id = auth.uid() OR 
        shared_with_id = auth.uid()
    );

DROP POLICY IF EXISTS project_shares_insert_policy ON project_shares;
CREATE POLICY project_shares_insert_policy ON project_shares
    FOR INSERT WITH CHECK (owner_id = auth.uid());

DROP POLICY IF EXISTS project_shares_update_policy ON project_shares;
CREATE POLICY project_shares_update_policy ON project_shares
    FOR UPDATE USING (
        owner_id = auth.uid() OR 
        shared_with_id = auth.uid()
    );

-- Presence policies (for real-time collaboration)
DROP POLICY IF EXISTS presence_policy ON presence;
CREATE POLICY presence_policy ON presence
    FOR ALL USING (
        user_id = auth.uid() OR
        project_id IN (
            SELECT id FROM projects WHERE 
            user_id = auth.uid() OR 
            id IN (SELECT project_id FROM project_shares WHERE shared_with_id = auth.uid() AND status = 'accepted')
        )
    );

-- =====================================================
-- REAL-TIME SUBSCRIPTIONS SETUP
-- =====================================================

-- Enable real-time for collaboration tables, handling cases where they might already be added.
DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.projects;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Table "projects" is already in the publication, skipping.';
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.financial_models;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Table "financial_models" is already in the publication, skipping.';
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.actual_performance;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Table "actual_performance" is already in the publication, skipping.';
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.actuals_period_entries;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Table "actuals_period_entries" is already in the publication, skipping.';
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.project_shares;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Table "project_shares" is already in the publication, skipping.';
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.presence;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Table "presence" is already in the publication, skipping.';
END;
$$;

-- =====================================================
-- VIEWS FOR OPTIMIZED QUERIES (Gemini Suggestions)
-- =====================================================

-- Project summary view with aggregated data
CREATE OR REPLACE VIEW project_summaries AS
SELECT 
    p.id,
    p.name,
    p.description,
    p.product_type,
    p.is_public,
    p.created_at,
    p.updated_at,
    COUNT(DISTINCT fm.id) as model_count,
    COUNT(DISTINCT ap.id) as performance_entries_count,
    COUNT(DISTINCT r.id) as risk_count,
    COUNT(DISTINCT ps.id) as share_count
FROM projects p
LEFT JOIN financial_models fm ON p.id = fm.project_id AND fm.deleted_at IS NULL
LEFT JOIN actual_performance ap ON p.id = ap.project_id
LEFT JOIN risks r ON p.id = r.project_id
LEFT JOIN project_shares ps ON p.id = ps.project_id AND ps.status = 'accepted'
WHERE p.deleted_at IS NULL
GROUP BY p.id, p.name, p.description, p.product_type, p.is_public, p.created_at, p.updated_at;

-- Model performance view with cached calculations
CREATE OR REPLACE VIEW model_performance AS
SELECT 
    fm.id,
    fm.name,
    fm.project_id,
    fm.assumptions,
    fm.results_cache,
    fm.created_at,
    fm.updated_at,
    COUNT(DISTINCT s.id) as scenario_count
FROM financial_models fm
LEFT JOIN scenarios s ON fm.id = s.model_id
WHERE fm.deleted_at IS NULL
GROUP BY fm.id, fm.name, fm.project_id, fm.assumptions, fm.results_cache, fm.created_at, fm.updated_at;

-- =====================================================
-- INITIALIZATION DATA
-- =====================================================

-- Drop the old function if it exists with a different return type
DROP FUNCTION IF EXISTS migrate_user_data(TEXT, TEXT, TEXT, TEXT, JSONB);

-- Create service role functions for data migration
CREATE OR REPLACE FUNCTION migrate_user_data(
    user_email TEXT,
    user_name TEXT DEFAULT NULL,
    user_picture TEXT DEFAULT NULL,
    user_company_domain TEXT DEFAULT NULL,
    user_preferences JSONB DEFAULT '{}'::jsonb
) RETURNS UUID AS $$
DECLARE
    user_id UUID;
BEGIN
    -- This function will be used during data migration
    -- Insert or update profile data
    INSERT INTO profiles (id, email, name, picture, company_domain, preferences)
    VALUES (gen_random_uuid(), user_email, user_name, user_picture, user_company_domain, user_preferences)
    ON CONFLICT (email) DO UPDATE SET
        name = EXCLUDED.name,
        picture = EXCLUDED.picture,
        company_domain = EXCLUDED.company_domain,
        preferences = EXCLUDED.preferences,
        updated_at = NOW()
    RETURNING id INTO user_id;
    
    RETURN user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- MIGRATION COMPLETE
-- =====================================================

-- Log successful migration
DO $$
BEGIN
    RAISE NOTICE 'Enhanced Supabase schema migration completed successfully';
    RAISE NOTICE 'Multi-AI optimizations applied:';
    RAISE NOTICE '- Supabase Auth integration with profiles table';
    RAISE NOTICE '- Advanced RLS policies for secure sharing';
    RAISE NOTICE '- Performance-optimized JSONB indexes';
    RAISE NOTICE '- Real-time collaboration support';
    RAISE NOTICE '- Comprehensive view layer for complex queries';
END $$;
