/**
 * Add Risk Modal - User-friendly risk creation for product managers
 */

import React, { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { CalendarIcon, AlertTriangle, CheckCircle2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { 
  SimpleRisk, 
  SimpleRiskCategory, 
  SimpleRiskPriority, 
  SimpleRiskStatus,
  SIMPLE_RISK_CATEGORIES, 
  RISK_PRIORITY_CONFIG,
  RISK_STATUS_CONFIG 
} from '@/types/simpleRisk';
import { toast } from "sonner";

interface AddRiskModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectId: string;
  onRiskAdded: (risk: SimpleRisk) => void;
}

export const AddRiskModal: React.FC<AddRiskModalProps> = ({
  isOpen,
  onClose,
  projectId,
  onRiskAdded
}) => {
  const [step, setStep] = useState<'category' | 'details' | 'action'>('category');
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    category: '' as SimpleRiskCategory,
    priority: 'medium' as SimpleRiskPriority,
    status: 'identified' as SimpleRiskStatus,
    potentialImpact: '',
    mitigationPlan: '',
    owner: '',
    targetDate: ''
  });

  const handleReset = () => {
    setStep('category');
    setFormData({
      title: '',
      description: '',
      category: '' as SimpleRiskCategory,
      priority: 'medium',
      status: 'identified',
      potentialImpact: '',
      mitigationPlan: '',
      owner: '',
      targetDate: ''
    });
  };

  const handleClose = () => {
    handleReset();
    onClose();
  };

  const handleSubmit = async () => {
    // Validate required fields
    if (!formData.title.trim() || !formData.description.trim() || !formData.category) {
      toast.error('Please fill in all required fields');
      return;
    }

    const newRisk: SimpleRisk = {
      id: `risk-${Date.now()}`, // Temporary ID - should be generated by backend
      projectId,
      ...formData,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      createdBy: 'current-user' // Should be actual user ID
    };

    try {
      // TODO: Save to database via API
      console.log('Saving risk:', newRisk);
      
      onRiskAdded(newRisk);
      toast.success('Risk added successfully!');
      handleClose();
    } catch (error) {
      console.error('Failed to add risk:', error);
      toast.error('Failed to add risk. Please try again.');
    }
  };

  const CategoryStep = () => (
    <div className="space-y-4">
      <div>
        <h3 className="text-lg font-medium mb-2">What type of risk is this?</h3>
        <p className="text-sm text-muted-foreground mb-4">
          Choose the category that best describes your concern:
        </p>
      </div>
      
      <div className="grid grid-cols-1 gap-3">
        {Object.entries(SIMPLE_RISK_CATEGORIES).map(([key, config]) => (
          <Card
            key={key}
            className={cn(
              "p-4 cursor-pointer border-2 transition-all hover:shadow-sm",
              formData.category === key ? "border-fortress-emerald bg-green-50" : "border-border hover:border-gray-300"
            )}
            onClick={() => setFormData(prev => ({ ...prev, category: key as SimpleRiskCategory }))}
          >
            <div className="flex items-start space-x-3">
              <span className="text-2xl">{config.icon}</span>
              <div className="flex-1">
                <h4 className="font-medium">{config.name}</h4>
                <p className="text-sm text-muted-foreground mt-1">{config.description}</p>
                <div className="mt-2">
                  <p className="text-xs text-muted-foreground">Examples:</p>
                  <ul className="text-xs text-muted-foreground mt-1">
                    {config.examples.slice(0, 2).map((example, index) => (
                      <li key={index}>• {example}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );

  const DetailsStep = () => (
    <div className="space-y-4">
      <div>
        <h3 className="text-lg font-medium mb-2">Tell us about this risk</h3>
        <p className="text-sm text-muted-foreground mb-4">
          Describe what you're concerned about and its potential impact.
        </p>
      </div>

      <div className="space-y-4">
        <div>
          <Label htmlFor="title" className="text-sm font-medium">
            Risk Title <span className="text-red-500">*</span>
          </Label>
          <Input
            id="title"
            placeholder="e.g., Key customer may not renew contract"
            value={formData.title}
            onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
            className="mt-1"
          />
        </div>

        <div>
          <Label htmlFor="description" className="text-sm font-medium">
            Description <span className="text-red-500">*</span>
          </Label>
          <Textarea
            id="description"
            placeholder="Provide more details about this risk..."
            value={formData.description}
            onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
            className="mt-1"
            rows={3}
          />
        </div>

        <div>
          <Label htmlFor="impact" className="text-sm font-medium">
            What could happen if this risk occurs?
          </Label>
          <Textarea
            id="impact"
            placeholder="e.g., Could lose 30% of projected revenue, delay launch by 2 months..."
            value={formData.potentialImpact}
            onChange={(e) => setFormData(prev => ({ ...prev, potentialImpact: e.target.value }))}
            className="mt-1"
            rows={2}
          />
        </div>

        <div>
          <Label className="text-sm font-medium">Priority Level</Label>
          <div className="grid grid-cols-3 gap-2 mt-2">
            {Object.entries(RISK_PRIORITY_CONFIG).map(([key, config]) => (
              <Card
                key={key}
                className={cn(
                  "p-3 cursor-pointer border-2 transition-all text-center",
                  formData.priority === key ? `${config.bgColor} ${config.borderColor}` : "border-border hover:border-gray-300"
                )}
                onClick={() => setFormData(prev => ({ ...prev, priority: key as SimpleRiskPriority }))}
              >
                <div className={cn("font-medium text-sm", formData.priority === key ? config.textColor : "")}>
                  {config.label}
                </div>
                <div className="text-xs text-muted-foreground mt-1">
                  {config.description}
                </div>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </div>
  );

  const ActionStep = () => (
    <div className="space-y-4">
      <div>
        <h3 className="text-lg font-medium mb-2">What's the plan?</h3>
        <p className="text-sm text-muted-foreground mb-4">
          Define how you'll handle this risk and who's responsible.
        </p>
      </div>

      <div className="space-y-4">
        <div>
          <Label htmlFor="mitigation" className="text-sm font-medium">
            Mitigation Plan
          </Label>
          <Textarea
            id="mitigation"
            placeholder="e.g., Schedule monthly check-ins with customer, prepare backup pricing options..."
            value={formData.mitigationPlan}
            onChange={(e) => setFormData(prev => ({ ...prev, mitigationPlan: e.target.value }))}
            className="mt-1"
            rows={3}
          />
        </div>

        <div>
          <Label htmlFor="owner" className="text-sm font-medium">
            Owner
          </Label>
          <Input
            id="owner"
            placeholder="Who's responsible for monitoring this risk?"
            value={formData.owner}
            onChange={(e) => setFormData(prev => ({ ...prev, owner: e.target.value }))}
            className="mt-1"
          />
        </div>

        <div>
          <Label htmlFor="targetDate" className="text-sm font-medium">
            Target Date (Optional)
          </Label>
          <Input
            id="targetDate"
            type="date"
            value={formData.targetDate}
            onChange={(e) => setFormData(prev => ({ ...prev, targetDate: e.target.value }))}
            className="mt-1"
          />
        </div>

        <div>
          <Label className="text-sm font-medium">Current Status</Label>
          <Select 
            value={formData.status} 
            onValueChange={(value) => setFormData(prev => ({ ...prev, status: value as SimpleRiskStatus }))}
          >
            <SelectTrigger className="mt-1">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Object.entries(RISK_STATUS_CONFIG).map(([key, config]) => (
                <SelectItem key={key} value={key}>
                  <div className="flex items-center space-x-2">
                    <span>{config.label}</span>
                    <span className="text-xs text-muted-foreground">- {config.action}</span>
                  </div>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>
    </div>
  );

  const renderStepContent = () => {
    switch (step) {
      case 'category': return <CategoryStep />;
      case 'details': return <DetailsStep />;
      case 'action': return <ActionStep />;
    }
  };

  const canProceed = () => {
    switch (step) {
      case 'category': return formData.category !== '';
      case 'details': return formData.title.trim() !== '' && formData.description.trim() !== '';
      case 'action': return true; // Action step is optional
    }
  };

  const getStepTitle = () => {
    switch (step) {
      case 'category': return 'Add New Risk - Step 1 of 3';
      case 'details': return 'Add New Risk - Step 2 of 3';
      case 'action': return 'Add New Risk - Step 3 of 3';
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{getStepTitle()}</DialogTitle>
          <DialogDescription>
            {step === 'category' && "Select the type of risk you want to track"}
            {step === 'details' && "Provide details about the risk and its potential impact"}
            {step === 'action' && "Define your response plan and ownership"}
          </DialogDescription>
        </DialogHeader>

        <div className="py-4">
          {/* Progress indicator */}
          <div className="flex items-center space-x-2 mb-6">
            <div className={cn(
              "w-8 h-8 rounded-full flex items-center justify-center text-xs font-medium",
              step === 'category' ? "bg-fortress-emerald text-white" : 
              ['details', 'action'].includes(step) ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-500"
            )}>
              {['details', 'action'].includes(step) ? <CheckCircle2 className="w-4 h-4" /> : '1'}
            </div>
            <div className={cn("h-0.5 w-12", ['details', 'action'].includes(step) ? "bg-green-300" : "bg-gray-200")} />
            <div className={cn(
              "w-8 h-8 rounded-full flex items-center justify-center text-xs font-medium",
              step === 'details' ? "bg-fortress-emerald text-white" : 
              step === 'action' ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-500"
            )}>
              {step === 'action' ? <CheckCircle2 className="w-4 h-4" /> : '2'}
            </div>
            <div className={cn("h-0.5 w-12", step === 'action' ? "bg-green-300" : "bg-gray-200")} />
            <div className={cn(
              "w-8 h-8 rounded-full flex items-center justify-center text-xs font-medium",
              step === 'action' ? "bg-fortress-emerald text-white" : "bg-gray-100 text-gray-500"
            )}>
              3
            </div>
          </div>

          {renderStepContent()}
        </div>

        <DialogFooter className="flex justify-between">
          <div className="flex space-x-2">
            <Button variant="outline" onClick={handleClose}>
              Cancel
            </Button>
            {step !== 'category' && (
              <Button
                variant="outline"
                onClick={() => {
                  if (step === 'details') setStep('category');
                  if (step === 'action') setStep('details');
                }}
              >
                Back
              </Button>
            )}
          </div>
          <div>
            {step !== 'action' ? (
              <Button
                onClick={() => {
                  if (step === 'category') setStep('details');
                  if (step === 'details') setStep('action');
                }}
                disabled={!canProceed()}
                className="bg-fortress-emerald hover:bg-fortress-emerald/90"
              >
                Next Step
              </Button>
            ) : (
              <Button
                onClick={handleSubmit}
                className="bg-fortress-emerald hover:bg-fortress-emerald/90"
              >
                Add Risk
              </Button>
            )}
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};